spring.application.name=stayhub_User

server.port=8083
grpc.server.port=9093

springdoc.api-docs.path=/api-docs-User
springdoc.swagger-ui.path=/swagger-ui.html

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

logging.level.org.springframework=INFO
logging.level.com.Angelh0.stayhub=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/stayhub_user
spring.datasource.username=${pg_user}
spring.datasource.password=${pg_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

grpc.server.security.enabled=false

jwt.secret=${JWT_SECRET}
