spring.application.name=stayhub_User

server.port=8083
grpc.server.port=9093

spring.datasource.url=jdbc:h2:file:./data/testdb_User
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console-User

springdoc.api-docs.path=/api-docs-User
springdoc.swagger-ui.path=/swagger-ui.html

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

logging.level.org.springframework=INFO
logging.level.com.Angelh0.stayhub=DEBUG
